version: '3.4'

services:
  mysql:
    container_name: mysqldb
    image: mysql:5.7
    profiles: [ "prod", "dev" ]
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: hemengo_distrib
      MYSQL_ROOT_PASSWORD: mauFJcuf5dhRMQrjj

  backend:
    container_name: hemengo_distrib_back
    profiles: [ "prod", "dev", "mobile" ]
    depends_on:
      - mysql
    build: ./back/
    ports:
      - 1201:1201
    restart: always
    environment:
      DB_HOST: mysql
      DB_NAME: hemengo_distrib
      DB_USER: root
      DB_PASS: mauFJcuf5dhRMQrjj

  adminer:
    image: adminer
    restart: always
    profiles: [ "dev" ]
    ports:
      - 8080:8080

  frontend:
    container_name: hemengo_distrib_front
    profiles: [ "prod", "dev" ]
    build: ./front/
    ports:
      - 4200:4200
    expose:
      - 4200
    tty: true
    depends_on:
      - backend

  ionic:
    container_name: ionic_app
    profiles: [ "prod", "dev", "mobile" ]
    build: ./front-mobile/
    ports:
      - 5000:5000
    expose:
      - 5000
    depends_on:
      - backend

volumes:
  db_data: {}
