pipeline {
    agent any

    stages {
        stage('Chekout') {
            steps {
                git url: 'https://github.com/KatzoArano/API-dnt2023', branch: 'main'
                echo 'Checkout Completed'
            }
        }
           stage('Build') {
            steps {
                sh 'sudo apt install npm'
                echo 'Building..'

            }
        }
        stage('Test') {
            steps {
                sh 'npm test'
                echo 'Testing..'

            }
        }
        stage('Deploy') {
            steps {
                sh 'npm run start'
                echo 'Deploying....'
            }
        }
    }
}