pipeline {
    agent any

    stages {
        stage('Chekout') {
            steps {
                git url: 'https://github.com/KatzoArano/API-dnt2023', branch: 'main'
                echo 'Checkout Completed'
            }
        }
           stage('Build') {
            steps {
                sh './back/cicd/build.sh'
                echo 'Building..'

            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'

            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}